# Generated by Django 3.0.5 on 2020-04-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_speedtest_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedtest_result',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
