# Generated by Django 3.0.5 on 2020-04-30 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200430_1406'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employees',
        ),
    ]
