# Generated by Django 3.0.5 on 2020-05-01 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_speedtest_result_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speedtest_result',
            old_name='file',
            new_name='logfile',
        ),
        migrations.RenameField(
            model_name='speedtest_result',
            old_name='download',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='speedtest_result',
            old_name='date',
            new_name='token',
        ),
        migrations.RemoveField(
            model_name='speedtest_result',
            name='upload',
        ),
    ]
