# Generated by Django 3.0.5 on 2020-05-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20200501_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedtest_result',
            name='logfile',
            field=models.FileField(default='', upload_to='file_uploads'),
        ),
    ]
